config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :flights, :bookings, :passengers
  # Defines the root path route ("/")
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arrivals, foreign_key: "arrival_id", class_name: "Flight"
  has_many :departures, foreign_key: "departure_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival, class_name: "Airport"
  belongs_to :departure, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def self.for_date(date)
    if date != ""
      where(date: date.to_date.all_day)
    else
      all
    end
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight])
    @booking = Booking.new
    params[:passengers].to_i.times { @booking.passengers.build }
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map{|airport| [airport.code, airport.id]}
    @booking = Booking.new

    if params[:departure].present? && params[:arrival].present?
      @flights = Flight.where(departure_id: params[:departure], arrival_id: params[:arrival]).for_date(params[:date])
    else
      @flights = nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1 class="mt-10 ml-20 font-bold text-4xl">Flight data</h1>

<p class="mt-10 ml-20 text-xl"><%="Flight ID: #{@flight.id} | Track: #{@flight.arrival.code} - #{@flight.departure.code}
 | Departure date: #{(@flight.date).strftime("%m/%d/%Y at %I:%M %p")} 
 | Flight duration: #{@flight.duration.strftime("%I:%M h")}" %></p>

<h2 class="mt-10 ml-20 font-bold text-2xl">Passengers data:</h2>
<%= form_with model: @booking, class: 'flex gap-5 flex-col ml-20 mt-10 ' do |form| %>
    <%= form.fields_for :passengers do |sub_form| %> 
      <div class="flex gap-5">
        <div class="flex flex-col">
          <%= sub_form.label :name, 'Name:' %>
          <%= sub_form.text_field :name, class: 'bg-gray-100' %>
        </div>
        <div class="flex flex-col">
          <%= sub_form.label :email, 'Email:'%>
          <%= sub_form.text_field :email, class: 'bg-gray-100' %>
        </div>
      </div>
    <% end %> 
  <%= form.hidden_field :flight_id, value: @flight.id %>
  <%= form.submit "Create booking", class: 'self-start rounded bg-violet-500 text-white px-5 py-1 cursor-pointer' %>
<%end %>

app/views/bookings/show.html.erb
<h1 class="mt-10 ml-20 font-bold text-4xl">Your booking</h1>

<h2 class="mt-10 ml-20 font-bold text-2xl">Flight</h2>
<p class="mt-10 ml-20 text-xl"><%="Flight ID: #{@flight.id} | Track: #{@flight.arrival.code} - #{@flight.departure.code}
 | Departure date: #{(@flight.date).strftime("%m/%d/%Y at %I:%M %p")} 
 | Flight duration: #{@flight.duration.strftime("%I:%M h")}" %></p>

<h2 class="mt-10 ml-20 font-bold text-2xl">Passengers</h2>

<% @booking.passengers.each do |passenger| %>
    <p class="mt-10 ml-20 text-xl"><%= "Name: #{passenger.name} | Email: #{passenger.email}" %></p>
<% end %>

<%= button_to "Generate ticket", {}, {class: 'ml-20 mt-10 rounded bg-violet-500 text-white px-5 py-1 cursor-pointer'}%>

app/views/flights/_flights.html.erb
<div class="search-results mt-10 ml-20 ">
  <% if @flights.empty? %>
    <p>No flights for this conditions.</p>
  <% else %>
    <h2 class="font-bold text-2xl mb-5">Available flights:</h3>
    <%= form_with url: new_booking_path, class: 'flex gap-5 flex-col', method: :get, data: {turbo: false} do |flight_form| %>
      <% @flights.each do |flight| %>
        <div class="chechbox-container">
          <%= flight_form.radio_button :flight, "#{flight.id}", {required: 'required'} %>
          <%= flight_form.label :flight, 
          "Departure: #{flight.departure.code} | Arrival: #{flight.arrival.code} | Datetime: #{flight.date}"%>
        </div>
      <% end %>
      <%= flight_form.hidden_field :passengers, value: params[:passengers] %>
      <div class="radio-button"><%= flight_form.submit "Continue", class: 'rounded bg-violet-500 text-white px-5 py-1 cursor-pointer'  %></div>
    <% end %>
  <% end %>
</div>

app/views/flights/index.html.erb
<h1 class="mt-10 ml-20 font-bold text-4xl">Flights</h1>

<%= form_with url: '/flights', class: 'flex gap-5 mt-10 ml-20', method: :get, data: {turbo_frame: 'flight_search'} do |form| %>
  <div class="input-container">
    <%= form.label :departure, "Departure: "  %>
    <%= form.select :departure, @airport_options, {}, { class: 'bg-gray-100', required: true } %>
  </div>
  <div class="input-container">
    <%= form.label :arrival, "Arrival: "  %>
    <%= form.select :arrival, @airport_options, {}, { class: 'bg-gray-100', required: true } %>
  </div>
  <div class="input-container">
    <%= form.label :passengers, "Passengers: "  %>
    <%= form.select :passengers, [1,2,3,4], {}, { class: 'bg-gray-100', required: true }%>
  </div>
  <div class="input-container">
    <%= form.label :date, "Date: (Optional)"  %>
    <%= form.date_field :date, class: 'bg-gray-100'%>
  </div>
  <%= form.submit "Search", class: 'rounded bg-violet-500 text-white px-5 py-1 cursor-pointer'%>
<% end %>

<% if @flights != nil %>
  <%= turbo_frame_tag "flight_search" do %>
    <%= render 'flights', flights: @flights %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>